mimir:
  structuredConfig:

    memberlist:
      join_members: []

    common:
      storage:
        backend: s3

        s3:
          endpoint: #Replace-with-your-s3-endpoint
          insecure: true

          access_key_id: admin
          secret_access_key: #REPLACE_WITH_YOUR_PASSWORD

          bucket_name: mimir

    blocks_storage:
      backend: s3

      s3:
        endpoint: #Replace-with-your-s3-endpoint
        insecure: true

        access_key_id: admin
        secret_access_key: #REPLACE_WITH_YOUR_PASSWORD

        bucket_name: mimir

    ruler_storage:
      backend: s3

      s3:
        endpoint: #Replace-with-your-s3-endpoint
        insecure: true

        access_key_id: admin
        secret_access_key: #REPLACE_WITH_YOUR_PASSWORD

        bucket_name: mimir

    alertmanager_storage:
      backend: s3

      s3:
        endpoint: #Replace-with-your-s3-endpoint
        insecure: true

        access_key_id: admin
        secret_access_key: #REPLACE_WITH_YOUR_PASSWORD

        bucket_name: mimir

    ingester:
      ring:
        replication_factor: 1

        kvstore:
          store: memberlist

    distributor:
      ring:
        kvstore:
          store: memberlist

    compactor:
      sharding_ring:
        kvstore:
          store: memberlist

    ruler:
      ring:
        kvstore:
          store: memberlist
