apiVersion: v1
kind: Pod
metadata:
  name: app2
  namespace: app
  labels:
    app: logs
spec:
  containers:
  - name: flog
    image: mingrammer/flog
    command: ["flog"]
    args: ["-f", "rfc3164", "-d", "5s", "-n", "100"]   
